### ISSUE TITLE
iframe embed

### ISSUE THREAD

**Issue by briand44** [ITS-UofIowa/police.uiowa.edu#4]
Hi Brian,
 
We are updating our lost and found system at DPS, and are currently trying to decide if we will use the iframe (below) or just link to the new lost and found system. This is where my lack of web knowledge comes in… we’d like to use the iframe, but I can’t figure out how to do it.
 
When you have time, would you be able to help OR insert it on this page (https://police.uiowa.edu/services/lost-found) under the crowd find text I have inserted? The iframe code is in the email below.
 
If this is not compatible with drupal, that’s fine too – I just wanted to check in to make sure it wasn’t just me.
 
Thanks for the help!
 
-Hayley
 
From: "Niles, Travis S" <travis-niles@uiowa.edu>
Date: Friday, April 12, 2019 at 12:09 PM
To: Hayley Bruce <hayley-bruce@uiowa.edu>, Dave Visin <dave-visin@uiowa.edu>
Cc: Beau Hartsock <beau-hartsock@uiowa.edu>
Subject: Fw: [External] Crowdfind web integration
 
Below are the options that were given.  If you could please take a look and determine which would be the easiest to implement or use.  
Thank you 
 
Travis Niles

Lost and Found Supervisor

UI Dept. of Public Safety

 
From: Sean Sutton <sean@crowdfind.com>
Sent: Friday, April 12, 2019 12:04 PM
To: Niles, Travis S
Subject: [External] Crowdfind web integration
 
Hey Travis,
 
I hope you're doing well. Apologies for not getting this off to you sooner. Below are both the iframe code and link that can be used to integrate the Crowdfind inventory page with your existing webpage. I've also included 2 examples of current campuses to show the different approaches. Both function exactly the same, it all comes down to your preference.
 
Iframe code: <iframe src="https://uiowa.v2.crowdfind.com/public/#!/dps/iframe" width="100%" height="768" frameBorder="0">Browser not compatible.</iframe>
 
link: https://uiowa.v2.crowdfind.com/public/#!/dps
 
 
Examples
 
Texas State University they have elected to use the iframe and have the Crowdfind page live on their existing page
 
UN Omaha they have the link on their page which pulls students out to the Crowdfind page
 
 
Let me know if there's anything else you need for me and I'm happy to help in any way I can. Also, when you are able, please send over the logos and I will get them into the account as soon as I can.
 
Thanks and have a great weekend,
 
Sean

**Comment by briand44** [comment]
Keegan, assigning this task to you for you to work on tomorrow.

**Comment by keeganjm1** [comment]
This should be complete
